### PR TITLE
Added permissions

### PR DESCRIPTION
**Pull request by Gamecrafter**
I believe you should add permissions in. Because server owners would want their players not to see the commands in /help like /version, /stop, and /list. On the other hand, OPs would need to be able to see all commands. Added the basic permission format.

### CODE REVIEW

**Comment by xxFlare** [comment]
Hmm, actually it should check if the play actually has permission for the real /help

**Comment by xxFlare** [comment]
Rather then creating a whole new permission

**Comment by xxFlare** [comment]
I suppose adding a new permission would be better though.

**Comment by Gamecrafter** [comment]
Yes, one for the custom /help, and one for the default /help.

**Pull request merged**
